For the unfiltered, consistent annotations, using the whole genome decoys.

Load packages

In [9]:
import numpy as np
import pandas as pd
import plotly.express as px

from sklearn.decomposition import PCA

PCA

Load the datasets created in R

In [10]:
norm_counts = pd.read_csv("C:/Users/Sebas/OneDrive/Dokument/Master courses/MASTER THESIS/R project-Master Thesis/salmon_mapping_normalized_counts_transcript_consistent_new_filtering_genotype_controlled_age_rank_fixed.csv", index_col=0)
norm_counts

,ERR12356072,ERR12383247,ERR12383248,ERR12383249,ERR12383250,ERR12383251,ERR12383252,ERR12383253,ERR12383254,ERR12383255,...,ERR12383308,ERR12383309,ERR12383310,ERR12383311,ERR12383312,ERR12383313,ERR12383314,ERR12383315,ERR12383316,ERR12383317
g2.t1,7.881771,8.058656,8.200582,8.989201,8.483403,9.207270,7.789775,8.047834,8.115469,8.778877,...,8.467024,8.155217,8.394621,7.710989,7.845979,8.337393,7.810269,8.165106,8.243547,9.002930
g3.t1,7.104422,6.979309,7.505145,7.205331,7.862185,7.617001,6.814318,7.493388,7.168586,7.414131,...,6.687924,7.029923,6.561583,5.951002,6.297211,6.402428,6.475258,7.676542,7.843207,7.471256
g4.t1,7.534024,7.541877,7.493801,7.001077,7.034639,6.998020,7.467329,7.343332,7.623867,6.989608,...,7.288582,7.315381,7.316950,7.502316,7.526480,7.383176,7.403942,6.984740,7.056760,6.423256
g5.t1,4.705132,5.077636,4.705132,5.572966,5.331813,5.399441,4.891187,4.705132,5.356088,6.052900,...,4.705132,4.705132,4.705132,4.999428,4.705132,4.880468,4.705132,5.898931,5.443409,4.705132
g6.t1,8.597134,9.003656,8.404115,8.018723,8.359932,8.217918,8.956325,8.652484,8.860414,8.413296,...,8.218780,8.231387,8.497639,8.768974,9.001573,9.025714,8.967964,8.287835,7.997991,7.895544
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
g34843.t1,5.568589,5.979236,6.108379,6.139920,5.703349,6.381351,5.816248,5.593577,5.767815,6.210711,...,5.385320,4.934162,5.212956,5.875921,5.120709,5.130703,5.592102,6.425403,5.974385,6.018597
g34884.t1,4.705132,4.946457,4.705132,4.705132,4.705132,5.333187,4.944951,4.705132,4.705132,4.705132,...,5.671103,5.393559,4.951411,4.967682,4.886300,5.200379,4.705132,5.241201,4.982608,5.315526
g34922.t1,5.300410,5.275054,5.259485,5.349363,5.287871,5.794722,5.344353,5.041779,5.331760,4.705132,...,6.597373,5.621284,5.379683,5.375077,5.083233,5.297305,5.320336,5.973553,4.705132,5.258290
g35167.t1,5.335532,5.399010,5.971149,6.040235,5.529231,6.069947,5.604051,5.694882,6.264427,5.234190,...,7.441429,5.600768,5.494096,5.582972,5.489341,5.284240,5.135388,7.469274,6.192084,6.607969
g35420.t1,4.921147,4.951358,4.705132,4.705132,4.705132,4.705132,4.960152,4.705132,4.705132,5.274777,...,5.352197,5.048081,4.971039,4.705132,4.705132,4.705132,5.062203,5.277201,5.128011,4.705132

In [11]:
#Metadata
metadata = pd.read_csv("C:/Users/Sebas/OneDrive/Dokument/Master courses/MASTER THESIS/R project-Master Thesis/dominance_meta_corrected_outlier_corrected.csv")

#make sure order matches norm_counts
metadata = metadata.set_index('Run')
metadata = metadata.reindex(norm_counts.columns)
# Now Run is the index, and metadata is aligned with counts
print("Metadata index (samples):", metadata.index[:5].tolist())
print("Counts columns:", norm_counts.columns[:5].tolist())
print("Match?", all(metadata.index == norm_counts.columns))
metadata

Metadata index (samples): ['ERR12356072', 'ERR12383247', 'ERR12383248', 'ERR12383249', 'ERR12383250']
Counts columns: ['ERR12356072', 'ERR12383247', 'ERR12383248', 'ERR12383249', 'ERR12383250']
Match? True

,Bases,BioProject,BioSample,Experiment,sample_name_incorrect,TF ID,Sample ID,Cross,Family,Sex,Reciprocal Genotype,Genotype,Pairwise Cross,original_fastq_name_R1,original_fastq_name_R2,Notes
ERR12356072,21027960416,PRJEB70958,SAMEA114860228,ERX11733017,Sample 1 males genotype BA heterozygote,TF2581-10-e3,10e 3,13:20 (M) + 42:13 (F),"2,3,4,",F,AB,AB Heterozygote,1,TF-2581-10-e3_S67_L001_R1_001.fastq.gz,TF-2581-10-e3_S67_L001_R2_001.fastq.gz,NaN
ERR12383247,14794943760,PRJEB70958,SAMEA114860213,ERX11759665,Sample 1 females genotype AA homozygote,TF2581-11,11,13:20 (M) + 42:13 (F),"2,3,4,",F,AB,AB Heterozygote,1,TF-2581-11_S9_L001_R1_001.fastq.gz,TF-2581-11_S9_L001_R2_001.fastq.gz,NaN
ERR12383248,15610248328,PRJEB70958,SAMEA114860214,ERX11759666,Sample 2 females genotype AA homozygote,TF2581-12,12,13:20 (M) + 42:13 (F),"2,3,4,",F,AB,AB Heterozygote,1,TF-2581-12_S10_L001_R1_001.fastq.gz,TF-2581-12_S10_L001_R2_001.fastq.gz,NaN
ERR12383249,9412089720,PRJEB70958,SAMEA114860215,ERX11759667,Sample 3 females genotype AA homozygote,TF2581-13,13,42:13 (M) + 13:20 (F),"1,4,8",M,BA,AB Heterozygote,1,TF-2581-13_S11_L001_R1_001.fastq.gz,TF-2581-13_S11_L001_R2_001.fastq.gz,NaN
ERR12383250,9959631122,PRJEB70958,SAMEA114860216,ERX11759668,Sample 1 males genotype AA homozygote,TF2581-14-e2,14e 2,42:13 (M) + 13:20 (F),"1,4,8",M,BA,AB Heterozygote,1,TF-2581-14-e2_S68_L001_R1_001.fastq.gz,TF-2581-14-e2_S68_L001_R2_001.fastq.gz,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ERR12383313,27406244206,PRJEB70958,SAMEA114860279,ERX11759731,Sample 1 females genotype FF homozygote,TF2581-71,71,4:18 + 4:18,"2,6,9",F,FF,FF Homozygote,3,TF-2581-71_S59_L001_R1_001.fastq.gz,TF-2581-71_S59_L001_R2_001.fastq.gz,"Had TF ID: TF2581-70, and Sample ID: 71 before..."
ERR12383314,13458064958,PRJEB70958,SAMEA114860280,ERX11759732,Sample 2 females genotype FF homozygote,TF2581-72,72,4:18 + 4:18,"2,6,9",F,FF,FF Homozygote,3,TF-2581-72_S60_L001_R1_001.fastq.gz,TF-2581-72_S60_L001_R2_001.fastq.gz,"Had TF ID: TF2581-71, and Sample ID: 72 before..."
ERR12383315,11890141660,PRJEB70958,SAMEA114860281,ERX11759733,Sample 3 females genotype FF homozygote,TF2581-7,7,13:20 (M) + 42:13 (F),"2,3,4,",M,AB,AB Heterozygote,1,TF-2581-7_S7_L001_R1_001.fastq.gz,TF-2581-7_S7_L001_R2_001.fastq.gz,NaN
ERR12383316,13692674262,PRJEB70958,SAMEA114860282,ERX11759734,Sample 1 males genotype FF homozygote,TF2581-8,8,13:20 (M) + 42:13 (F),"2,3,4,",M,AB,AB Heterozygote,1,TF-2581-8_S8_L001_R1_001.fastq.gz,TF-2581-8_S8_L001_R2_001.fastq.gz,NaN
ERR12383317,14658478416,PRJEB70958,SAMEA114860283,ERX11759735,Sample 2 males genotype FF homozygote,TF2581-9e,9e,13:20 (M) + 42:13 (F),"2,3,4,",M,AB,AB Heterozygote,1,TF-2581-9e_S61_L001_R1_001.fastq.gz,TF-2581-9e_S61_L001_R2_001.fastq.gz,NaN

In [12]:
# create transpose
vst_t = norm_counts.T

pca = PCA(n_components=2)
pca_scores = pca.fit_transform(vst_t)

pca_df = metadata.copy()
pca_df['PC1'] = pca_scores[:,0]
pca_df['PC2'] = pca_scores[:,1]

# Explained variance
pc1_var = pca.explained_variance_ratio_[0] * 100
pc2_var = pca.explained_variance_ratio_[1] * 100

# Define your own color mapping
color_map = {'M': 'blue', 'F': 'red'}  

fig = px.scatter(
    pca_df,
    x='PC1',
    y='PC2',
    color='Sex',  
    color_discrete_map=color_map,          
    hover_name=pca_df.index,
    title=f"Salmon-Map: Male vs. Female PCA of VST-normalized counts"
)

fig.update_layout(
    xaxis_title=f"PC1 ({pca.explained_variance_ratio_[0]*100:.1f}% var)",
    yaxis_title=f"PC2 ({pca.explained_variance_ratio_[1]*100:.1f}% var)",
    width=1000
)

#fig.write_image("salmon_map_pca.svg")
fig.show()

Volcano Plot

In [13]:
results_full_annot = pd.read_csv("C:/Users/Sebas/OneDrive/Dokument/Master courses/MASTER THESIS/R project-Master Thesis/salmon_map_dominance_DE_sex_results_new_filtering_genotype_controlled_age_rank_fixed.csv", float_precision='legacy')
results_full_annot

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,transcript_id,gene_id,seqname,chr_loc,...,eggNOG_OGs,species_tree_birth_node,gene_tree_birth_node,birth_type,age_rank,age_category,node_depth_from_root,branch_length,n_copies_in_og,n_species_in_og
0,248.420188,0.640709,0.110526,5.796904,6.755020e-09,1.316673e-08,g2.t1,g2,utg000001l,A,...,"2FBM0@1|root,2TCUK@2759|Eukaryota,398E5@33154|...",C_maculatus_filtered_proteinfasta_TE_filtered,n3,duplication,9.0,recent,0.758700,0.061748,2.0,8.0
1,92.726112,0.650988,0.104454,6.232321,4.595741e-10,9.353175e-10,g3.t1,g3,utg000001l,A,...,"KOG2101@1|root,KOG2101@2759|Eukaryota,396Y9@33...",C_maculatus_filtered_proteinfasta_TE_filtered,n9,duplication,9.0,recent,0.758700,0.061748,2.0,14.0
2,136.044931,-0.600974,0.070022,-8.582668,9.269779e-18,2.387530e-17,g4.t1,g4,utg000001l,A,...,"COG0181@1|root,KOG2892@2759|Eukaryota,38D6W@33...",C_maculatus_filtered_proteinfasta_TE_filtered,n13,duplication,9.0,recent,0.758700,0.061748,2.0,14.0
3,3.332468,2.699629,0.718636,3.756600,1.722376e-04,2.671748e-04,g5.t1,g5,utg000001l,A,...,"KOG2761@1|root,KOG2761@2759|Eukaryota,38F7R@33...",C_maculatus_filtered_proteinfasta_TE_filtered,n8,duplication,9.0,recent,0.758700,0.061748,2.0,12.0
4,381.084979,-0.875080,0.046175,-18.951587,4.284679e-80,3.659726e-79,g6.t1,g6,utg000001l,A,...,"2E6V3@1|root,2SDHR@2759|Eukaryota",N8,NaN,mrca_inferred,6.0,intermediate,0.629385,0.171468,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17569,20.275098,0.319252,0.150056,2.127555,3.337403e-02,4.238130e-02,g34843.t1,g34843,utg003648l,U,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17570,1.364118,2.068769,0.590743,3.501981,4.618132e-04,6.956768e-04,g34884.t1,g34884,utg003700l,U,...,"2D3G7@1|root,2SRFN@2759|Eukaryota,3AMW9@33154|...",C_maculatus_filtered_proteinfasta_TE_filtered,n17,duplication,9.0,recent,0.758700,0.061748,23.0,4.0
17571,8.286716,1.984267,0.355927,5.574921,2.476423e-08,4.718367e-08,g34922.t1,g34922,utg003714l,U,...,NaN,C_maculatus_filtered_proteinfasta_TE_filtered,n43,duplication,9.0,recent,0.758700,0.061748,22.0,6.0
17572,19.121063,2.284212,0.326813,6.989347,2.761695e-12,6.049015e-12,g35167.t1,g35167,utg003885l,U,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17573,3.504696,1.065212,0.357173,2.982341,2.860533e-03,4.036436e-03,g35420.t1,g35420,utg003980l,U,...,"KOG1075@1|root,KOG1075@2759|Eukaryota,39TZY@33...",C_maculatus_filtered_proteinfasta_TE_filtered,n31,duplication,9.0,recent,0.758700,0.061748,13.0,6.0

In [14]:
# Replace the zeros in padj with 1e-308 avoid log10 issues
results_full_annot["padj_safe"] = results_full_annot["padj"].replace(0, 1e-308).fillna(1)

# Add the negative log 10 padj for plotting
results_full_annot["neglog10_padj"] = -np.log10(results_full_annot["padj_safe"])


# Add significance to differentially expressed genes 
results_full_annot["significant"] = (
    (results_full_annot["padj"] < 0.05) &
    (results_full_annot["log2FoldChange"].abs() > 1)
)

# Add a label to the significant genes
results_full_annot["label"] = results_full_annot["gene_id"].where(results_full_annot["significant"], "")

results_full_annot

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,transcript_id,gene_id,seqname,chr_loc,...,age_rank,age_category,node_depth_from_root,branch_length,n_copies_in_og,n_species_in_og,padj_safe,neglog10_padj,significant,label
0,248.420188,0.640709,0.110526,5.796904,6.755020e-09,1.316673e-08,g2.t1,g2,utg000001l,A,...,9.0,recent,0.758700,0.061748,2.0,8.0,1.316673e-08,7.880522,False,
1,92.726112,0.650988,0.104454,6.232321,4.595741e-10,9.353175e-10,g3.t1,g3,utg000001l,A,...,9.0,recent,0.758700,0.061748,2.0,14.0,9.353175e-10,9.029041,False,
2,136.044931,-0.600974,0.070022,-8.582668,9.269779e-18,2.387530e-17,g4.t1,g4,utg000001l,A,...,9.0,recent,0.758700,0.061748,2.0,14.0,2.387530e-17,16.622051,False,
3,3.332468,2.699629,0.718636,3.756600,1.722376e-04,2.671748e-04,g5.t1,g5,utg000001l,A,...,9.0,recent,0.758700,0.061748,2.0,12.0,2.671748e-04,3.573204,True,g5
4,381.084979,-0.875080,0.046175,-18.951587,4.284679e-80,3.659726e-79,g6.t1,g6,utg000001l,A,...,6.0,intermediate,0.629385,0.171468,1.0,4.0,3.659726e-79,78.436551,False,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17569,20.275098,0.319252,0.150056,2.127555,3.337403e-02,4.238130e-02,g34843.t1,g34843,utg003648l,U,...,NaN,NaN,NaN,NaN,NaN,NaN,4.238130e-02,1.372826,False,
17570,1.364118,2.068769,0.590743,3.501981,4.618132e-04,6.956768e-04,g34884.t1,g34884,utg003700l,U,...,9.0,recent,0.758700,0.061748,23.0,4.0,6.956768e-04,3.157592,True,g34884
17571,8.286716,1.984267,0.355927,5.574921,2.476423e-08,4.718367e-08,g34922.t1,g34922,utg003714l,U,...,9.0,recent,0.758700,0.061748,22.0,6.0,4.718367e-08,7.326208,True,g34922
17572,19.121063,2.284212,0.326813,6.989347,2.761695e-12,6.049015e-12,g35167.t1,g35167,utg003885l,U,...,NaN,NaN,NaN,NaN,NaN,NaN,6.049015e-12,11.218315,True,g35167
17573,3.504696,1.065212,0.357173,2.982341,2.860533e-03,4.036436e-03,g35420.t1,g35420,utg003980l,U,...,9.0,recent,0.758700,0.061748,13.0,6.0,4.036436e-03,2.394002,True,g35420

In [15]:
fig = px.scatter(
    results_full_annot,
    x="log2FoldChange",
    y="neglog10_padj",
    hover_name="transcript_id",
    hover_data=["padj", "HOG", "PFAMs"],  # Use the columns that already exist
    color="significant",
    color_discrete_map={True: "red", False: "blue"},
    title="Salmon-Map: Volcano Plot (Male vs. Female Transcript Expression)"
)

fig.update_traces(textposition='top center', textfont_size=8)

fig.update_layout(
    xaxis_title="log2 Fold Change (male vs female)",
    yaxis_title="-log10(padj (FDR))",
    width = 1000
)

# Horizontal FDR=0.05 cutoff
padj_cut = -np.log10(0.05)

fig.add_hline(
    y=padj_cut,
    line_dash="dash",
    line_color="grey",
    annotation_text="padj = 0.05",
    annotation_position="bottom right"
)

# Vertical log2FC cutoffs
fig.add_vline(
    x=-1,
    line_dash="dash",
    line_color="grey",
    annotation_text="log2FC = -1",
    annotation_position="top left"
)
fig.add_vline(
    x=1,
    line_dash="dash",
    line_color="grey",
    annotation_text="log2FC = 1",
    annotation_position="top right"
)
#fig.write_image("salmon_map_volcano.svg")
fig.show()


#DE genes
sig_counts = results_full_annot["significant"].sum()
higher_in_m = ((results_full_annot["significant"]) & 
               (results_full_annot["log2FoldChange"] > 0)).sum()
higher_in_f = ((results_full_annot["significant"]) & 
               (results_full_annot["log2FoldChange"] < 0)).sum()

print(f"Total significant transcripts: {sig_counts}")
print(f"Higher in males: {higher_in_m}")
print(f"Higher in females: {higher_in_f}")

Total significant transcripts: 7270
Higher in males: 5070
Higher in females: 2200

Significant Transcripts

In [16]:
sig_transcripts = results_full_annot[results_full_annot["significant"]]

sig_transcripts

,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj,transcript_id,gene_id,seqname,chr_loc,...,age_rank,age_category,node_depth_from_root,branch_length,n_copies_in_og,n_species_in_og,padj_safe,neglog10_padj,significant,label
3,3.332468,2.699629,0.718636,3.756600,1.722376e-04,2.671748e-04,g5.t1,g5,utg000001l,A,...,9.0,recent,0.758700,0.061748,2.0,12.0,2.671748e-04,3.573204,True,g5
5,70.718212,-1.039030,0.089153,-11.654489,2.176813e-31,7.787918e-31,g7.t1,g7,utg000001l,A,...,1.0,ancient,0.000000,0.000000,1.0,12.0,7.787918e-31,30.108579,True,g7
6,475.721002,1.120124,0.059428,18.848397,3.028815e-79,2.541218e-78,g8.t1,g8,utg000001l,A,...,1.0,ancient,0.000000,0.000000,1.0,12.0,2.541218e-78,77.594958,True,g8
7,97.175715,1.341896,0.124766,10.755269,5.597042e-27,1.811622e-26,g9.t1,g9,utg000001l,A,...,8.0,recent,0.696952,0.035914,2.0,14.0,1.811622e-26,25.741932,True,g9
11,237.620281,-4.015786,0.186764,-21.501956,1.492615e-102,1.902623e-101,g13.t1,g13,utg000001l,A,...,8.0,recent,0.696952,0.035914,1.0,14.0,1.902623e-101,100.720647,True,g13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17566,1.283803,1.996209,0.614968,3.246035,1.170246e-03,1.707534e-03,g34618.t1,g34618,utg003533l,U,...,NaN,NaN,NaN,NaN,NaN,NaN,1.707534e-03,2.767631,True,g34618
17570,1.364118,2.068769,0.590743,3.501981,4.618132e-04,6.956768e-04,g34884.t1,g34884,utg003700l,U,...,9.0,recent,0.758700,0.061748,23.0,4.0,6.956768e-04,3.157592,True,g34884
17571,8.286716,1.984267,0.355927,5.574921,2.476423e-08,4.718367e-08,g34922.t1,g34922,utg003714l,U,...,9.0,recent,0.758700,0.061748,22.0,6.0,4.718367e-08,7.326208,True,g34922
17572,19.121063,2.284212,0.326813,6.989347,2.761695e-12,6.049015e-12,g35167.t1,g35167,utg003885l,U,...,NaN,NaN,NaN,NaN,NaN,NaN,6.049015e-12,11.218315,True,g35167
17573,3.504696,1.065212,0.357173,2.982341,2.860533e-03,4.036436e-03,g35420.t1,g35420,utg003980l,U,...,9.0,recent,0.758700,0.061748,13.0,6.0,4.036436e-03,2.394002,True,g35420